### ISSUE TITLE
Access to undeclared static property

### ISSUE THREAD

**Issue by fearrr** [klaravel/ntrust#10]
After update to new version, i get this

```
ErrorException in \vendor\klaravel\ntrust\src\Ntrust\Traits\NtrustUserTrait.php line 14:

Access to undeclared static property: App\User::$roleProfile 
(View: ..\resources\views\sections\menu.blade.php)

```

in view i use 

```
@role('admin')
@endrole

@role(['creator', 'moderator'])
@endrole

@role('user')
@endrole
```

**Comment by fearrr** [comment]
And I found the solution in the text of the error)
`protected $roleProfile = 'user';` changed to `protected static $roleProfile = 'user';`

Maybe this version changes must be major (2.0.0), as no backward compatibility? Or you think that updates are too small for this?

**Comment by fearrr** [comment]
I use 1.\* version mask.

**Comment by klaravel** [comment]
@fearrr 

Sorry for that one.

Actually it was small bug for soft delete one and I have fixed that one with help of one other developer and I those I change to version 2.0.0 but it might be really big changed that's why I made 1.1.0.

But sure next time I will take care of that one.
