### ISSUE TITLE
Admin.php

### ISSUE THREAD

**Issue by ghost** [klaravel/ntrust#13]
I am following the docs but I am after getting stuck.
After installing via composer and updating provider and alias if I run

`$ php artisan ntrust:migration Admin`

I get an error `Class 'App\Admin' not found`

So I `$ php artisan create:model Admin`

Do I need to manually add the relationships between admin, roles and users here? If so, what relationships or is that up to me?
Admin: belongsTo('App\User') ?
User: hasMany('App\Admin') ?
User: hasMany('App\Role') ?
Admin: hasMany('App\Role') ?

If I run `$ php artisan ntrust:migration admin` here I can create `Tables: admin_roles, admin_role_user, admin_permissions, admin_permission_role`

but I try and migrate I get an error 
```
  [Illuminate\Database\QueryException]                                                                  
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `admin_role_user` add constraint `admin_role_user_user_id_foreign` foreign key (`user_id`) references `admins` (`id`) on delete cascade on update cascade)                                                           

  [PDOException]                                                          
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint `
```

Am I doing something wrong or are the docs missing something?
Only admin_roles & admin_role_user get migrated.

**Comment by klaravel** [comment]
What is connection between User and Admin? Both should be diffrent user type.

If you like to add Admin for ntrust then use follwing code.
You have to create three model manully.

`Admin` user model

``` php
<?php

use Klaravel\Ntrust\Traits\NtrustUserTrait;

class Admin extends Authenticatable
{
    use NtrustUserTrait; // add this trait to your user model

    /*
     * Role profile to get value from ntrust config file.
     */
    protected static $roleProfile = 'admin';

    ...
}
```

``` php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Klaravel\Ntrust\Traits\NtrustRoleTrait;

class AdminRole extends Model
{
    use NtrustRoleTrait;

    /*
     * Role profile to get value from ntrust config file.
     */
    protected static $roleProfile = 'admin';
}
```

``` php
<?php 

namespace App;

use Illuminate\Database\Eloquent\Model;
use Klaravel\Ntrust\Traits\NtrustPermissionTrait;

class AdminPermission extends Model
{
    use NtrustPermissionTrait;

    /*
     * Role profile to get value from ntrust config file.
     */
    protected static $roleProfile = 'admin';
}
```

Migration file should looks like below one. There should be create 4 tables for admin. 
You have to create `Admin` table manually. Depend on your requirement. 

[2016_10_05_010232_admin_ntrust_setup_tables.txt](https://github.com/klaravel/ntrust/files/572671/2016_10_05_010232_admin_ntrust_setup_tables.txt)

Let me know if you have more questions.

**Comment by andrietri** [comment]
i get same error 
Class 'App\User' not found                                                                vendor/klaravel/ntrust/src/Ntrust/Commands/MigrationCommand.php on line 95 

how to solve that?

**Comment by klaravel** [comment]
@andrietri  Can you please give more detail about your code or can you please show me your code?

**Comment by andrietri** [comment]
@klaravel my code just default first time install laravel 5.3. i follow installiation klaravel/ntrust and run 
"php artisan ntrust:migration" but error message like that

**Comment by andrietri** [comment]
@klaravel 
`PHP Fatal error:  
Class 'App\User' not found in /opt/lampp/htdocs/atlasmu/vendor/kla                                                          ravel/ntrust/src/Ntrust/Commands/MigrationCommand.php on line 95`

`[Symfony\Component\Debug\Exception\FatalErrorException]  
 Class 'App\User' not found`

**Comment by klaravel** [comment]
@andrietri  Do you have App\User class?

What is your default profile in config\ntrust.php?

try to replace `'model' => 'App\User',` to `'model' => App\User::class,` in your ntrust.php config file

**Comment by andrietri** [comment]
yes i have, my default profile in config\ntust.php
`'defaults' => [
        'profile' => 'user',
 ],`

i try to replace that but still not work
`[Symfony\Component\Debug\Exception\FatalErrorException] 
Class 'App\User::class' not found`

**Comment by klaravel** [comment]
Can you please join Gitter chat and message me there and I will help you there. my username is `ajmerainfo`

**Comment by manearaluca** [comment]
Hello,
Did anybody solved this problem?
I have the same issue.
Thanks,
Raluca

**Comment by ajmerainfo** [comment]
@manearaluca 

What problem do you have?

**Comment by andrietri** [comment]
I dont have any problem

Pada tanggal 22 Apr 2017 2.57 AM, "Keyur Ajmera" <notifications@github.com>
menulis:

**Comment by manearaluca** [comment]
Hello, I had to create the model Users inside App folder. So, no problem!
Thank you!
