### ISSUE TITLE
BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::attachRole()

### ISSUE THREAD

**Issue by cmayorgahilario** [klaravel/ntrust#14]
BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::attachRole()

in 

$user->attachRole($admin);

**Comment by klaravel** [comment]
Can you please show me your full user model?

**Comment by ajmerainfo** [comment]
I am closing issue right now. If anything you can reopen.
