### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by angallego** [klaravel/ntrust#16]
Hi! 
When I try to access the permissions of a role, show this error: 
> Class name must be a valid object or a string

`$perms = $ role->perms()->get();`

In fact, $role->roleProfile is null

**Comment by klaravel** [comment]
@angallego Can you please show me your user and role model code ?

**Comment by angallego** [comment]
Of course!
**User.php**
`<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Kodeine\Metable\Metable;
use Klaravel\Ntrust\Traits\NtrustUserTrait;

class User extends Authenticatable
{
    use Metable, NtrustUserTrait;

```
protected $metaTable = 'users_meta';

protected static $roleProfile = 'user';

protected $table = 'users';

protected $fillable = ['first_name', 'last_name', 'email', 'phone', 'fax', 'username', 'password', 'status', 'token'];

protected $hidden = ['password', 'remember_token'];


public function groups()
{
  return $this->belongsToMany('App\UserGroup', 'user_user_group', 'user_id');
}

public function group()
{
  return $this->hasOne('App\UserGroup', 'id_extra', 'id');
}

public function userGroup()
{
  return $this->hasOne('App\UserUserGroup');
}
```

}`

**Role.php**
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Klaravel\Ntrust\Traits\NtrustRoleTrait;

class Role extends Model
{
    use NtrustRoleTrait;

```
protected $table = 'roles';
protected $fillable = ['name', 'display_name', 'description'];

protected static $roleProfile = 'user';
```

}
`

**Permission.php**
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Klaravel\Ntrust\Traits\NtrustPermissionTrait;

class Permission extends Model
{
    use NtrustPermissionTrait;

```
protected $table = 'permissions';
protected $fillable = ['name', 'display_name', 'description'];

protected static $roleProfile = 'user';
```

}
`

**Comment by klaravel** [comment]
Try below code in your config/ntrust.php file

``` php
<?php
return [
    'defaults' => [
        'profile' => 'user',
    ],
    'profiles' => [
        'user' => [
            'table' => 'users',
            'model' => App\User::class,
            'role' => App\Role::class,
            'roles_table' => 'roles',
            'permission' => App\Permission::class,
            'permissions_table' => 'permissions',
            'permission_role_table' => 'permission_role',
            'role_user_table' => 'role_user',
            'user_foreign_key' => 'user_id',
            'role_foreign_key' => 'role_id',
            'permission_foreign_key' => 'permission_id',
        ],
    ],
];
```

`$role->roleProfile` will be null. because of static variable.

If still not working then let me know what version of php are you using?

Check this code with tinker after get `$role` parame `$perms = $role->perms`

**Comment by klaravel** [comment]
@angallego Let me know if you still need help for this one.

I going to close this issue.
