### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by ebottis** [klaravel/ntrust#17]
Hi, I am getting this error when trying to determine a user's role running the following code:

$user->hasRole('admin'); 

I have 2 role types, 'user' and 'admin' and I'm not using permissions.

I am sure this is something I am doing incorrectly but since I saw the last thread was left unopen I thought I should post.

**User Model:**

<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Klaravel\Ntrust\Traits\NtrustUserTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    use NtrustUserTrait;
    /*
     * Role profile to get value from ntrust config file.
     */
    protected static $roleProfile = 'user';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

**Role Model:**

<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Klaravel\Ntrust\Traits\NtrustRoleTrait;

class Role extends Model
{
    use NtrustRoleTrait;

    /*
     * Role profile to get value from ntrust config file.
     */
    protected static $roleProfile = 'user';

}

**Comment by xitude** [comment]
I have the same issue when using it in views like I used to use Entrust
```
@if(Ntrust::can(['can-access-admin']))
```

**Comment by xitude** [comment]
This is actually an issue in [Entrust](https://github.com/Zizaco/entrust#troubleshooting). 
http://stackoverflow.com/questions/35785441/laravel-5-2-with-entrust-class-name-must-be-a-valid-object-or-a-string

> When trying to use the EntrustUserTrait methods, you encounter the error which looks like
> 
> **Class name must be a valid object or a string**
> 
> then probably you don't have published Entrust assets or something went wrong when you did it. First of all check that you have the entrust.php file in your config directory. If you don't, then try php artisan vendor:publish and, if it does not appear, manually copy the /vendor/zizaco/entrust/src/config/config.php file in your config directory and rename it entrust.php.

**Comment by klaravel** [comment]
I will review today later on and fix this one.

**Comment by buglinjo** [comment]
@ebottis If you look into source code of the package, there is called `$this->roleProfile` but in your model is decleared and set statically so the value will be `null` and you will have that error.

To fix this please remove `static` from `protected static $roleProfile = 'profile-name';`.

**Comment by ajmerainfo** [comment]
@ebottis  where do you see `$this->roleProfile`?
