### ISSUE TITLE
Multi Auth migration create

### ISSUE THREAD

**Issue by buglinjo** [klaravel/ntrust#19]
I'm using Laravel 5.3 multiauth guards.
I have edited `ntrust.php` in `config` directory.
When I run `php artisan ntrust:migration admin` or `php artisan ntrust:migration user`
it creates migrations with not `admin_user_id` or `site_user_id` it creates with default value `user_id`.

Same with `role_id` and `permission_id`

**Comment by ajmerainfo** [comment]
Hi @buglinjo,

I know it's too late reply but with that it does not matter with that column name. 

Please reopen this issue if you see any issue.
