### ISSUE TITLE
Access to undeclared static property User::$staticRoleProfile

### ISSUE THREAD

**Issue by brunocamarggo** [klaravel/ntrust#20]
I'm trying to remove users from database, so in my controller I do:

`$ User = User :: find ($ id); `
`$ User-> delete (); `

But I am always getting the error: "Access to undeclared static property User :: $ staticRoleProfile"

Someone can help me? I'm very noob with PHP / Laravel (I do not know if it's a complex problem or not, sorry). 

Thanks a lot.

**Comment by ajmerainfo** [comment]
@brunocamarggo  Can you please show your use model code here?

**Comment by brunocamarggo** [comment]
`<?php

namespace estoque;

use Illuminate\Notifications\Notifiable;
use Klaravel\Ntrust\Traits\NtrustUserTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable{
    use Notifiable;
    use NtrustUserTrait; 

    protected $roleProfile = 'user';
    
    protected  $fillable = [
        'name', 'email', 'password',
    ];

    protected  $hidden = [
        'password', 'remember_token',
    ];

    public function role(){
        return $this->hasMany('estoque\Role');
    }
}
`

**Comment by ajmerainfo** [comment]
Can you please try with replace below code?

`protected static $roleProfile = 'user';`

https://github.com/klaravel/ntrust#role

**Comment by brunocamarggo** [comment]
@ajmerainfo If I replace this code I get the error "Class name must be a valid object or a string "

**Comment by ajmerainfo** [comment]
Can you please show full error?

**Comment by brunocamarggo** [comment]
@ajmerainfo Thanks for the attention. I didn't find the error but I restarted all the configuration and now all works fine. Thanks a lot. 

Can you close this issue, please?
