### ISSUE TITLE
Migration to klaravel/ntrust from Zizaco/entrust

### ISSUE THREAD

**Issue by physio** [klaravel/ntrust#21]
is it possibile migrate an existing project from Zizaco/entrust to klaravel/ntrust?

**Comment by ajmerainfo** [comment]
@physio  Yes you can. 

You have to change manually `[config/ntrust.php](https://github.com/klaravel/ntrust/blob/master/src/config/ntrust.php)` file.

And need to add migration if it's for admin user or multiple user.

One more thing need to add below code for your user/admin and role & permission class.

```php
/*
 * Role profile to get value from ntrust config file.
 */
protected static $roleProfile = 'user';
```
