### ISSUE TITLE
$roleProfile variable is not present in user object

### ISSUE THREAD

**Issue by kbalajijan1** [klaravel/ntrust#25]
As mentioned in readme.md, I updated User model with `protected static $roleProfile = 'user';` but it's not present in the user object. If I use without static, the variable is present in user object.

Since the static variable is not working I get _Class name must be a valid object or a string_ error. Laravel version is 5.3.29

Please advice

**Comment by ajmerainfo** [comment]
@kbalajijan1  

Let me know do you still have same issue?
