### ISSUE TITLE
[BadMethodCallException]   Call to undefined method Illuminate\Database\Query\Builder::attachPermissio   ns()

### ISSUE THREAD

**Issue by ghost** [klaravel/ntrust#28]
Hello, when i at**tach the one permission to user** or **set multi permission** , i have one error , this my code:

`$user->attachPermissions([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]);`
or
`$user->attachPermission(1);`

May you help me ?

```
[BadMethodCallException]
  Call to undefined method Illuminate\Database\Query\Builder::attachPermissio
  ns()
```

**Comment by ajmerainfo** [comment]
@DevMehmetNuri 

Actually with this module made for user directly connected with roles and roles connected with permission. 
So without role permission can't attache with user.

If you have role and permissions under any role and user attached to role then you can checkout user has either role or permission directly.

Let me know if that help.
