### ISSUE TITLE
ntrust vs laravel built-in authorization

### ISSUE THREAD

**Issue by matijakovacevic** [klaravel/ntrust#29]
Seems similar to laravel in-built authorization.

What are the pros of this package versus built-in functionalities?
https://laravel.com/docs/5.4/authorization

**Comment by ajmerainfo** [comment]
Similar functionality you have to hard code on code with this plugin you can manage it on databasse also you can manage roles and permission from your backend/admin side.

**Comment by matijakovacevic** [comment]
That about sums it up.
Thank you.
