### ISSUE TITLE
Edit role permissions issue

### ISSUE THREAD

**Issue by kjareena** [klaravel/ntrust#32]
Hi ,
**ntrust** package is really wonderful . but i have a small issue on this, i am getting below error when i am going to edit a role with added permissions.
  {!! Form::select('permissions[]',$permissions,$role->permission->pluck('id'),['id'=>'multiple-checkboxes','multiple'=>true] ) !!}

Call to a member function pluck() on null (View: D:\projects\boom\resources\views\roles\edit.blade.php)

Please help me is am doing any this wrong to call added permissions.

**Comment by klaravel** [comment]
@kjareena 

Can you please try `$role->perms->pluck('id')` ?

**Comment by kjareena** [comment]
Thank You so much .... 
But

$role->perms->pluck('id')  getting 
Illuminate\Support\Collection Object ( [items:protected] => Array ( [0] => 2 [1] => 3 ) )

$permissions getting 
Illuminate\Support\Collection Object ( [items:protected] => Array ( [3] => permissions [2] => roles [1] => users ) )


Here i am not getting selected values......

**Comment by kjareena** [comment]
Thank you so much i got the answer.

$role->perms->pluck('id')->toArray()
