### ISSUE TITLE
Route level if condition else redirects to dashboad.

### ISSUE THREAD

**Issue by kjareena** [klaravel/ntrust#33]
Hi,

This is not issue, i am asking you a suggestion.

my route:

Route::group(['middleware' => ['permission:roles']], function() { Route::resource("/roles", "RoleController"); });

In this above route working fine but, if a person do not have roles permission it redirects 404 page or dashboard page. 

Controller level i can restrict and redirects to dashboard. But i can't understand how to write if condition in route level.

**Comment by ajmerainfo** [comment]
@kjareena 

It's totally up to you.

You can define whatever you like with create your own middle ware and set in `Kernel.php` with your own path.

Change your path `\Klaravel\Ntrust\Middleware\`.
```
'role' => \Klaravel\Ntrust\Middleware\NtrustRole::class,
'permission' => \Klaravel\Ntrust\Middleware\NtrustPermission::class,
'ability' => \Klaravel\Ntrust\Middleware\NtrustAbility::class,
```

Change Code Example: NtrustPermission  `Klaravel\Ntrust\Middleware\NtrustPermission`

```
public function handle($request, Closure $next, $permissions)
	{
		if (auth()->guest() || !$request->user()->can(explode('|', $permissions))) {
			abort(403); // Change here wherever you want to send user. like dashboard or login or 404
		}
		return $next($request);
	}
```

**Comment by kjareena** [comment]
Thank You so much .... Very helpful to me.
