### ISSUE TITLE
fyi?

### ISSUE THREAD

**Issue by aneeshsudhakaran** [klaravel/ntrust#5]
1. Is this support multiple user role for one user?
2. Can we manage user permissions and manage roles for user side and admin side?

**Comment by klaravel** [comment]
1. Yes. 
2. Yes. Correct.

You can make separate tables for maintain both or more users.
There is artisan command for make that.

Let me know if you still have any question about it.

**Comment by aneeshsudhakaran** [comment]
Thank you for the reply. 
I'm new in Laravel, have to do a project with multi user/roles.
Do you have any working demo/code package?

**Comment by klaravel** [comment]
I am working right now on that one for make live demo with admin panel.

But right now you have to read documents. No other options. It's very easy and clean.

Let me know if you get any error or if you stuck.

**Comment by aneeshsudhakaran** [comment]
Ok
