### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by brandenwagner** [klaravel/ntrust#7]
I have the ntrust.php in the config folder, but i am still getting this error.

**Comment by ajmerainfo** [comment]
Can you please show some code or send more detail?
So I can help you with that.

**Comment by brandenwagner** [comment]
```
in Model.php line 939
at Model->belongsToMany(null, null, 'user_id', null) in NtrustUserTrait.php line 55
at User->roles() in NtrustUserTrait.php line 20
at User->cachedRoles() in NtrustUserTrait.php line 104
at User->hasRole('admin', false) in Ntrust.php line 36
at Ntrust->hasRole('admin') in Facade.php line 237
at Facade::__callStatic('hasRole', array('admin')) in a0f6258539f84f37e2041eaf8c8fe1ff558e277f.php line 71
```

The only issue i could potentially see, which i have already checked.
My models are in 

```
    App\Models\Role
   App\Models\Permission

```

I have already updated that in the ntrust config on 

```
   'role' => 'App\Models\Role',
    'permission' => 'App\Models\Permission',
```

I also tried putting them in the normal directory.
I am trying to integrate this with laravel spark if that might make a difference.

Im pretty sure this is the line its getting caught on:
  `<div id="page-wrapper" class="{{Ntrust::hasRole('admin') ? '' : 'no-sidebar'}}">
`

**Comment by klaravel** [comment]
Can you please show me your model full page code and config/ntrust.php?

I have tested same thing and it's working fine for me.

**Comment by brandenwagner** [comment]
[ntrust.txt](https://github.com/klaravel/ntrust/files/526050/ntrust.txt)
[Permission.txt](https://github.com/klaravel/ntrust/files/526051/Permission.txt)
[Role.txt](https://github.com/klaravel/ntrust/files/526052/Role.txt)

**Comment by klaravel** [comment]
What is location of your `User` model?

**Comment by brandenwagner** [comment]
App\User
App\Team
are the only two models in the app directory

**Comment by klaravel** [comment]
One last thing might help. Migration file.

**Comment by brandenwagner** [comment]
[2016_10_13_004625_user_ntrust_setup_tables.txt](https://github.com/klaravel/ntrust/files/526061/2016_10_13_004625_user_ntrust_setup_tables.txt)

**Comment by klaravel** [comment]
Try this file and let me know 

[ntrust.txt](https://github.com/klaravel/ntrust/files/526072/ntrust.txt)

**Comment by brandenwagner** [comment]
Same error no change.

**Comment by klaravel** [comment]
Can you please come to gitter chat room? Or need to see more code to troubleshoot.

Still not sure what is issue. Might be php version or something else. 

Many people have same issue but I have fix that issue in my code.

http://stackoverflow.com/questions/35785441/laravel-5-2-with-entrust-class-name-must-be-a-valid-object-or-a-string

**Comment by klaravel** [comment]
Let me know if it's fix?

**Comment by brandenwagner** [comment]
Still having the same issue. Sorry, i was at work all day.
