### ISSUE TITLE
delete role throw error

### ISSUE THREAD

**Issue by riseno** [klaravel/ntrust#8]
When deleting role record, an error occurred.

```
FatalThrowableError in NtrustRoleTrait.php line 95:
Using $this when not in object context
```

After I check the line 95 of NtrustRoleTrait.php, seems you are calling `$this` within the static method.

Any solution for that?

**Comment by klaravel** [comment]
@riseno  Thank you for found issue. 

Can you please verify in your local vendor code with that `self::roleProfile` ?

Let me know if that working fine then I will update code and release new version with bug free.

**Comment by klaravel** [comment]
Please ignore my last comment. Let me check other solution.

Are you using softDelete?

**Comment by klaravel** [comment]
I have fixed on new release. 
Can you please try now with below changes.
It's might be bad coding practice but it will work for now. 

Take `v1.0.4`

Please add following line in your three model files (Users, Role, Permission)

```
protected static $staticRoleProfile = 'user or [Your Profile]';
```

Let me know if you have more issues.

**Comment by riseno** [comment]
Thanks for your reply and fixes, but, there is still error on it.

By calling the class static property, it should be called like this

```
self::$staticRoleProfile
```

Otherwise, below error will be thrown.

```
Undefined class constant 'staticRoleProfile'
```

**Comment by klaravel** [comment]
Thanks for finding bug.

Fixed.

Can you please try now?

**Comment by riseno** [comment]
Cool! all good now. thx a lot
